apiVersion: v1
kind: Service
metadata:
  name: aftr-webserver-lb
  labels:
    app: aftr
    service: webserver-lb
spec:
  type: LoadBalancer
  selector:
    app: aftr
    service: webserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 4000
